### ISSUE TITLE
Bard fieldToArray fails with buttons

### ISSUE THREAD

**Issue by danielbrodin** [tdwesten/statamic-builder#11]
Hi,

I have just started to evaluate the extension (which I like so far), but noticed an error with the Bard field when doing this, which I guess is the correct way to use it
```php
Bard::make('...')->buttons([BardButton::H2, BardButton::H3])
```

The error is with this line
```php
public function fieldToArray(): Collection
    {
        return collect([
            'buttons' => $this->buttons->map->value()->toArray(),
```

Not sure why it's mapping over the values instead of just `$this->buttons->toArray()`?

**Comment by tdwesten** [comment]
Hi @danielbrodin,

Thank you for trying out this addon, it's really awesome!

I appreciate you bringing up this bug, and I believe I've addressed it in the `11-bard-fieldtoarray-fails-with-buttons` branch. Could you please test it by running:
```bash
composer require tdwesten/statamic-builder:dev-11-bard-fieldtoarray-fails-with-buttons
```

Many thanks!

**Comment by danielbrodin** [comment]
That works :)

This however only makes it work when using the enum, I'm thinking it would be a good idea to also support normal strings in case one would extend bard with a custom button which then wouldn't exist in the `BardButton` enum.

**Comment by tdwesten** [comment]
I aim to offer numerous autocompletion hints by including enums for non-boolean options. Thanks for your feedback about adding custom buttons. Now, you can add strings or `BarsButton` enums.
