### ISSUE TITLE
Missing fields/functions for Terms

### ISSUE THREAD

**Issue by MatthiasvanPijkeren** [tdwesten/statamic-builder#21]
At least maxItems is missing

**Comment by tdwesten** [comment]
Hi @MatthiasvanPijkeren, 

The `->maxItems(1)` is added via a MaxItems trait and there is a test: https://github.com/tdwesten/statamic-builder/blob/70ec46e245a3a547a0865ba83ac2237ed25b8cb4/tests/Unit/Fields/TermsTest.php#L41

Are you missing more functions?
